# -*- coding: utf-8 -*-
"""SQLITE3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d37KPB5--HOklz9iqY9SsNvnu-7BRrtT
"""

import sqlite3

import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime
import random

conn=sqlite3.connect("sales_data.db")

cursor=conn.cursor()

cursor.execute("DROP TABLE IF EXISTS sales")

cursor.execute('''CREATE TABLE sales (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    date TEXT NOT NULL,
    product TEXT NOT NULL,
    category TEXT NOT NULL,
    quantity INTEGER CHECK(quantity >= 0),
    price REAL CHECK(price >= 0),
    region TEXT NOT NULL,
    payment_method TEXT NOT NULL)''')

products = [
    ("Pen", "Stationery", 5.0),
    ("Pencil", "Stationery", 2.0),
    ("Notebook", "Stationery", 25.0),
    ("Eraser", "Stationery", 1.5),
    ("Marker", "Stationery", 10.0),
    ("Highlighter", "Stationery", 12.0),
    ("Stapler", "Office Supplies", 50.0),
    ("Tape", "Office Supplies", 15.0),
    ("Folder", "Office Supplies", 20.0),
    ("Glue Stick", "Stationery", 8.0)
]

regions=["North", "South","West", "East"]

payment_methods = ["Cash", "Credit Card", "UPI", "Net Banking"]

random.seed(42)

sales_data=[]

for _ in range(40):
    product, category, price = random.choice(products)
    quantity = random.randint(1, 15)
    date = datetime.strptime(f"2023-{random.randint(1,12):02d}-{random.randint(1,28):02d}", "%Y-%m-%d").strftime("%Y-%m-%d")
    region = random.choice(regions)
    payment = random.choice(payment_methods)
    sales_data.append((date, product, category, quantity, price, region, payment))

cursor.executemany('''
INSERT INTO sales (date, product, category, quantity, price, region, payment_method)
VALUES (?, ?, ?, ?, ?, ?, ?)
''', sales_data)

conn.commit()

query = '''SELECT product,category, SUM(quantity) AS total_units_sold, ROUND(SUM(quantity * price), 2) AS total_revenue
FROM sales GROUP BY product, category ORDER BY total_revenue DESC'''

df = pd.read_sql_query(query, conn)

print("Product-wise Revenue Summary:\n")
print(df.to_string(index=False))

plt.figure(figsize=(10,6))

bars = plt.bar(df['product'], df['total_revenue'], color='slateblue')
plt.title("Total Revenue by Product")
plt.xlabel("Product")
plt.ylabel("Revenue (₹)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.grid(axis='y', linestyle='--', alpha=0.7)
for bar in bars:
    plt.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 2, f"₹{bar.get_height():.0f}", ha='center', fontsize=9)
plt.savefig("revenue_chart_detailed.png")
plt.show()

top_row = df.iloc[0]

print(f"\n🔍 Insight: '{top_row['product']}' from category '{top_row['category']}' generated the most revenue — ₹{top_row['total_revenue']}'")

from google.colab import files
files.download("sales_data.db")